services:
    ongr_demo.magento.cart.controller:
        class: ONGR\DemoMagentoBundle\Controller\CartController
        calls:
            - [ setTemplating, [ @templating ] ]
            - [ setManager, [ @es.manager.magento ] ]