services:
    ongr_demo.magento.cart.controller:
        class: ONGR\DemoMagentoBundle\Controller\CartController
        calls:
            - [ setTemplating, [ @templating ] ]
            - [ setCart, [ @ongr_demo.magento.cart ] ]
